In [3]:
import numpy as np

a = np.array(range(1,11))
b = np.array(range(10,101,10))
a+b,a-b,a*b,a/b

c = a+b
c.shape
c.size

10

In [10]:
import numpy as np

heights = [1.83, 1.76, 1.78]
weights = [86, 74, 64]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights/(np_heights**2)
print('대상자들의 BMI :',bmi)
print(bmi[bmi>25])

대상자들의 BMI : [25.68007405 23.88946281 20.19946976]
[25.68007405]


In [9]:
scores = np.array([88,72,93,94,89,78,99])
scores[4:-1]

array([89, 78])

In [14]:
np_array = np.array([[1,2,3], [4,5,6] ,[7,8,9]])
np_array >5
np_array[np_array >5]

array([6, 7, 8, 9])

In [19]:
players =[[170, 76.4]
         ,[183, 86.2]
         ,[181, 78.5]
         ,[176, 80.1]]

np_players = np.array(players)
print('몸무게가 80이상인 선수 정보',np_players[np_players[:,1] > 80.0]) #[:,1] 두번째 열
print('키카 180이상인 선수 정보',np_players[np_players[:,0] > 180])

몸무게가 80이상인 선수 정보 [[183.   86.2]
 [176.   80.1]]
키카 180이상인 선수 정보 [[183.   86.2]
 [181.   78.5]]


In [20]:
np.random.randn(5)

array([ 1.45108526,  1.66874767, -0.86790089, -0.14973126,  0.65893794])

In [2]:
import numpy as np

players = np.zeros((100,3)) #배열 0으로 채워서 생성
players[:,0] = 10 * np.random.randn(100) + 175
players[:,1] = 10 * np.random.randn(100) + 70
players[:,2] = np.floor(10 * np.random.randn(100)) + 22 #소수점이하 없애주는 함수 floor

heights = players[:,0]
print('신장 평균값',np.mean(heights))
print('신장 중앙값',np.median(heights))

weights = players[:,1]
print('체중 평균값',np.mean(weights))
print('체중 중앙값',np.median(weights))

ages = players[:,2]
print('나이 평균값',np.mean(ages))
print('나이 중앙값',np.median(ages))

신장 평균값 174.52979982238077
신장 중앙값 175.81344934039902
체중 평균값 71.29724328940256
체중 중앙값 71.21707343379333
나이 평균값 21.9
나이 중앙값 22.5


In [20]:
num_arr = np.arange(1,21)
print(num_arr)
print(num_arr[::-1])
print(np.flip(num_arr))
print('모든 원소의 합 :',sum(num_arr))
print(num_arr.reshape(5,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
모든 원소의 합 : 210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [26]:
n_arr = np.arange(25).reshape(5,5)
print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [29]:
n_arr[0,0]
n_arr[4,4]

24

In [52]:
print(n_arr[0:2,:])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [32]:
n_arr[2:5,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
n_arr[0:5:2,0:5:2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [51]:
n_arr[0:2,:].reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
a = np.random.randn(3,3,3)
print(a)

[[[ 0.87633893 -0.7131743   0.42793173]
  [ 0.46003527  0.29962707 -0.12883495]
  [ 0.39275948 -1.25101242  1.50069077]]

 [[-0.28870376 -0.08721909 -0.23620719]
  [-0.86524827  1.28944505 -0.54951213]
  [-0.36939375 -1.84637786  0.45071757]]

 [[-1.12589555  1.24366844  0.52421736]
  [ 1.23073607  1.75289793 -1.25982443]
  [ 1.37757488 -0.06733566 -1.21486132]]]


In [55]:
np.max(a)

1.7528979333030004

In [56]:
np.argmax(a)

22

In [72]:
a = np.zeros((5,5))
a[0:5:2,0:5:2] = 1
a[1:5:2,1:5:2] = 1
print(a)
print('행방향 성분의 합 :\n',a.sum(axis=0))

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]
행방향 성분의 합 :
 [3. 2. 3. 2. 3.]


In [1]:
# 10.4-1
import numpy as np
n_arr = np.arange(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        if n_arr[i][j] % 2 == 0:
            n_arr[i][j] = 1
        else :
            n_arr[i][j] = 0
print(n_arr)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [80]:
a = np.arange(32).reshape(4,4,2)
a = a.flatten()
print('10번쨰 원소 : ',a[9])
print('20번째 원소 :',a[19])

10번쨰 원소 :  9
20번째 원소 : 19


In [25]:
# 10.6
import numpy as np
x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1,10) for i in range(100)]
x3 = [i + np.random.randint(1,50) for i in range(100)]
x4 = [np.random.randint(1,100) for i in range(100)]
result1 = np.corrcoef(x1,x2)
result2 = np.corrcoef(x1,x3)
result3 = np.corrcoef(x1,x4)
result4 = np.corrcoef([x1,x2,x3,x4])
print(result1)
print(result2)
print(result3)
print(result4)

[[1.         0.99571475]
 [0.99571475 1.        ]]
[[1.         0.89051759]
 [0.89051759 1.        ]]
[[ 1.         -0.19077036]
 [-0.19077036  1.        ]]
[[ 1.          0.99571475  0.89051759 -0.19077036]
 [ 0.99571475  1.          0.87777782 -0.18714925]
 [ 0.89051759  0.87777782  1.         -0.12001583]
 [-0.19077036 -0.18714925 -0.12001583  1.        ]]
